version: '3'
services:
  master:
    build:
      context: master
    ports:
      - "5001:5001"
    environment:
      - SECONDARY_URLS=http://secondary1:5002//secondary1,http://secondary2:5003/secondary2
    depends_on:
      - secondary1
      - secondary2
    networks:
      - my-network

  secondary1:
    build:
      context: secondary1
    ports:
      - "5002:5002"
    networks:
      - my-network

  secondary2:
    build:
      context: secondary2
    ports:
      - "5003:5003"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge